overrides:
  fast-uri: 3.1.2

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  msw: false
  sharp: false
  unrs-resolver: false
