export type { SeedCategory, SeedGender, SeedCalendar, SeedInput } from '../../src/lib/kasi/seed-runner';
import type { SeedInput } from '../../src/lib/kasi/seed-runner';

export const KASI_SEED_INPUTS: SeedInput[] = [
  // ── NORMAL 50건 ──
  { id: 'N001', category: 'normal', input: { year: 1990, month: 3,  day: 15, hour: 14, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'N002', category: 'normal', input: { year: 1985, month: 7,  day: 22, hour: 8,  minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'N003', category: 'normal', input: { year: 1993, month: 11, day: 5,  hour: 20, minute: 45, gender: '남', calendar: 'solar' } },
  { id: 'N004', category: 'normal', input: { year: 1978, month: 4,  day: 30, hour: 6,  minute: 15, gender: '여', calendar: 'solar' } },
  { id: 'N005', category: 'normal', input: { year: 2001, month: 9,  day: 12, hour: 16, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'N006', category: 'normal', input: { year: 1967, month: 1,  day: 18, hour: 10, minute: 30, gender: '여', calendar: 'solar' } },
  { id: 'N007', category: 'normal', input: { year: 1995, month: 6,  day: 3,  hour: 22, minute: 20, gender: '남', calendar: 'solar' } },
  { id: 'N008', category: 'normal', input: { year: 1982, month: 12, day: 25, hour: 4,  minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'N009', category: 'normal', input: { year: 1970, month: 8,  day: 7,  hour: 18, minute: 10, gender: '남', calendar: 'solar' } },
  { id: 'N010', category: 'normal', input: { year: 2005, month: 2,  day: 14, hour: 12, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'N011', category: 'normal', input: { year: 1988, month: 5,  day: 20, hour: 7,  minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'N012', category: 'normal', input: { year: 1975, month: 10, day: 11, hour: 15, minute: 45, gender: '여', calendar: 'solar' } },
  { id: 'N013', category: 'normal', input: { year: 1999, month: 3,  day: 28, hour: 9,  minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'N014', category: 'normal', input: { year: 1963, month: 7,  day: 4,  hour: 23, minute: 50, gender: '여', calendar: 'solar' } },
  { id: 'N015', category: 'normal', input: { year: 2003, month: 11, day: 19, hour: 3,  minute: 15, gender: '남', calendar: 'solar' } },
  { id: 'N016', category: 'normal', input: { year: 1980, month: 4,  day: 8,  hour: 11, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'N017', category: 'normal', input: { year: 1956, month: 9,  day: 27, hour: 17, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'N018', category: 'normal', input: { year: 1992, month: 1,  day: 13, hour: 5,  minute: 45, gender: '여', calendar: 'solar' } },
  { id: 'N019', category: 'normal', input: { year: 1973, month: 6,  day: 30, hour: 19, minute: 20, gender: '남', calendar: 'solar' } },
  { id: 'N020', category: 'normal', input: { year: 2007, month: 2,  day: 5,  hour: 13, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'N021', category: 'normal', input: { year: 1987, month: 8,  day: 17, hour: 21, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'N022', category: 'normal', input: { year: 1969, month: 12, day: 9,  hour: 8,  minute: 15, gender: '여', calendar: 'solar' } },
  { id: 'N023', category: 'normal', input: { year: 1997, month: 4,  day: 23, hour: 16, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'N024', category: 'normal', input: { year: 1960, month: 10, day: 16, hour: 2,  minute: 30, gender: '여', calendar: 'solar' } },
  { id: 'N025', category: 'normal', input: { year: 2010, month: 5,  day: 31, hour: 10, minute: 45, gender: '남', calendar: 'solar' } },
  { id: 'N026', category: 'normal', input: { year: 1983, month: 3,  day: 6,  hour: 14, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'N027', category: 'normal', input: { year: 1954, month: 7,  day: 20, hour: 7,  minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'N028', category: 'normal', input: { year: 2000, month: 11, day: 1,  hour: 22, minute: 15, gender: '여', calendar: 'solar' } },
  { id: 'N029', category: 'normal', input: { year: 1976, month: 6,  day: 14, hour: 4,  minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'N030', category: 'normal', input: { year: 1991, month: 1,  day: 29, hour: 18, minute: 45, gender: '여', calendar: 'solar' } },
  { id: 'N031', category: 'normal', input: { year: 1965, month: 9,  day: 10, hour: 11, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'N032', category: 'normal', input: { year: 2004, month: 3,  day: 25, hour: 20, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'N033', category: 'normal', input: { year: 1979, month: 8,  day: 3,  hour: 6,  minute: 20, gender: '남', calendar: 'solar' } },
  { id: 'N034', category: 'normal', input: { year: 1958, month: 12, day: 18, hour: 15, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'N035', category: 'normal', input: { year: 1996, month: 5,  day: 7,  hour: 9,  minute: 10, gender: '남', calendar: 'solar' } },
  { id: 'N036', category: 'normal', input: { year: 1971, month: 10, day: 24, hour: 23, minute: 30, gender: '여', calendar: 'solar' } },
  { id: 'N037', category: 'normal', input: { year: 2008, month: 4,  day: 16, hour: 3,  minute: 45, gender: '남', calendar: 'solar' } },
  { id: 'N038', category: 'normal', input: { year: 1984, month: 7,  day: 31, hour: 13, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'N039', category: 'normal', input: { year: 1961, month: 2,  day: 8,  hour: 17, minute: 15, gender: '남', calendar: 'solar' } },
  { id: 'N040', category: 'normal', input: { year: 1998, month: 11, day: 21, hour: 5,  minute: 30, gender: '여', calendar: 'solar' } },
  { id: 'N041', category: 'normal', input: { year: 1974, month: 6,  day: 12, hour: 21, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'N042', category: 'normal', input: { year: 2002, month: 9,  day: 29, hour: 8,  minute: 40, gender: '여', calendar: 'solar' } },
  { id: 'N043', category: 'normal', input: { year: 1966, month: 3,  day: 17, hour: 16, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'N044', category: 'normal', input: { year: 1989, month: 7,  day: 4,  hour: 10, minute: 20, gender: '여', calendar: 'solar' } },
  { id: 'N045', category: 'normal', input: { year: 1952, month: 12, day: 3,  hour: 2,  minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'N046', category: 'normal', input: { year: 2006, month: 4,  day: 28, hour: 19, minute: 15, gender: '여', calendar: 'solar' } },
  { id: 'N047', category: 'normal', input: { year: 1977, month: 8,  day: 15, hour: 7,  minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'N048', category: 'normal', input: { year: 1994, month: 2,  day: 22, hour: 14, minute: 50, gender: '여', calendar: 'solar' } },
  { id: 'N049', category: 'normal', input: { year: 1968, month: 10, day: 9,  hour: 20, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'N050', category: 'normal', input: { year: 2009, month: 6,  day: 17, hour: 11, minute: 0,  gender: '여', calendar: 'solar' } },

  // ── BOUNDARY 30건 ──
  { id: 'B001', category: 'boundary', input: { year: 1990, month: 2,  day: 4,  hour: 5,  minute: 15, gender: '남', calendar: 'solar' } },
  { id: 'B002', category: 'boundary', input: { year: 1990, month: 2,  day: 3,  hour: 23, minute: 59, gender: '여', calendar: 'solar' } },
  { id: 'B003', category: 'boundary', input: { year: 1990, month: 2,  day: 5,  hour: 0,  minute: 1,  gender: '남', calendar: 'solar' } },
  { id: 'B004', category: 'boundary', input: { year: 1985, month: 3,  day: 21, hour: 12, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'B005', category: 'boundary', input: { year: 1985, month: 3,  day: 20, hour: 23, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'B006', category: 'boundary', input: { year: 1993, month: 4,  day: 20, hour: 8,  minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'B007', category: 'boundary', input: { year: 1993, month: 4,  day: 19, hour: 22, minute: 45, gender: '남', calendar: 'solar' } },
  { id: 'B008', category: 'boundary', input: { year: 1999, month: 6,  day: 21, hour: 14, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'B009', category: 'boundary', input: { year: 1999, month: 6,  day: 20, hour: 23, minute: 55, gender: '남', calendar: 'solar' } },
  { id: 'B010', category: 'boundary', input: { year: 2001, month: 8,  day: 7,  hour: 6,  minute: 30, gender: '여', calendar: 'solar' } },
  { id: 'B011', category: 'boundary', input: { year: 2001, month: 8,  day: 6,  hour: 23, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'B012', category: 'boundary', input: { year: 1995, month: 9,  day: 23, hour: 10, minute: 20, gender: '여', calendar: 'solar' } },
  { id: 'B013', category: 'boundary', input: { year: 1995, month: 9,  day: 22, hour: 23, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'B014', category: 'boundary', input: { year: 1988, month: 11, day: 7,  hour: 9,  minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'B015', category: 'boundary', input: { year: 1988, month: 11, day: 6,  hour: 22, minute: 45, gender: '남', calendar: 'solar' } },
  { id: 'B016', category: 'boundary', input: { year: 1970, month: 12, day: 22, hour: 3,  minute: 30, gender: '여', calendar: 'solar' } },
  { id: 'B017', category: 'boundary', input: { year: 1970, month: 12, day: 21, hour: 23, minute: 50, gender: '남', calendar: 'solar' } },
  { id: 'B018', category: 'boundary', input: { year: 1982, month: 1,  day: 1,  hour: 0,  minute: 5,  gender: '여', calendar: 'solar' } },
  { id: 'B019', category: 'boundary', input: { year: 1981, month: 12, day: 31, hour: 23, minute: 55, gender: '남', calendar: 'solar' } },
  { id: 'B020', category: 'boundary', input: { year: 1990, month: 3,  day: 6,  hour: 0,  minute: 2,  gender: '여', calendar: 'solar' } },
  { id: 'B021', category: 'boundary', input: { year: 1990, month: 3,  day: 5,  hour: 23, minute: 58, gender: '남', calendar: 'solar' } },
  { id: 'B022', category: 'boundary', input: { year: 1975, month: 5,  day: 21, hour: 23, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'B023', category: 'boundary', input: { year: 1975, month: 5,  day: 22, hour: 1,  minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'B024', category: 'boundary', input: { year: 2003, month: 2,  day: 4,  hour: 10, minute: 12, gender: '여', calendar: 'solar' } },
  { id: 'B025', category: 'boundary', input: { year: 2003, month: 2,  day: 3,  hour: 10, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'B026', category: 'boundary', input: { year: 1997, month: 7,  day: 7,  hour: 11, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'B027', category: 'boundary', input: { year: 1997, month: 7,  day: 6,  hour: 23, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'B028', category: 'boundary', input: { year: 2000, month: 1,  day: 1,  hour: 0,  minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'B029', category: 'boundary', input: { year: 1960, month: 2,  day: 5,  hour: 6,  minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'B030', category: 'boundary', input: { year: 2010, month: 8,  day: 7,  hour: 23, minute: 45, gender: '여', calendar: 'solar' } },

  // ── EDGE 20건 ──
  { id: 'E001', category: 'edge', input: { year: 1995, month: 8,  day: 15, hour: 12, minute: 0,  gender: '남', calendar: 'lunar' } },
  { id: 'E002', category: 'edge', input: { year: 1990, month: 1,  day: 1,  hour: 6,  minute: 0,  gender: '여', calendar: 'lunar' } },
  { id: 'E003', category: 'edge', input: { year: 2000, month: 4,  day: 15, hour: 10, minute: 0,  gender: '남', calendar: 'lunar' } },
  { id: 'E004', category: 'edge', input: { year: 1985, month: 7,  day: 7,  hour: 14, minute: 0,  gender: '여', calendar: 'lunar' } },
  { id: 'E005', category: 'edge', input: { year: 1975, month: 5,  day: 5,  hour: 9,  minute: 0,  gender: '남', calendar: 'lunar' } },
  { id: 'E006', category: 'edge', input: { year: 1950, month: 6,  day: 25, hour: 4,  minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'E007', category: 'edge', input: { year: 1910, month: 8,  day: 29, hour: 12, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'E008', category: 'edge', input: { year: 2025, month: 12, day: 31, hour: 23, minute: 59, gender: '여', calendar: 'solar' } },
  { id: 'E009', category: 'edge', input: { year: 2030, month: 6,  day: 15, hour: 14, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'E010', category: 'edge', input: { year: 1900, month: 1,  day: 1,  hour: 12, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'E011', category: 'edge', input: { year: 1990, month: 3,  day: 15, hour: 12, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'E012', category: 'edge', input: { year: 1988, month: 6,  day: 29, hour: 0,  minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'E013', category: 'edge', input: { year: 1993, month: 9,  day: 30, hour: 23, minute: 59, gender: '남', calendar: 'solar' } },
  { id: 'E014', category: 'edge', input: { year: 1980, month: 2,  day: 29, hour: 10, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'E015', category: 'edge', input: { year: 2000, month: 2,  day: 29, hour: 15, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'E016', category: 'edge', input: { year: 1976, month: 8,  day: 15, hour: 8,  minute: 0,  gender: '여', calendar: 'lunar', leap: true } },
  { id: 'E017', category: 'edge', input: { year: 1963, month: 11, day: 22, hour: 18, minute: 30, gender: '남', calendar: 'solar' } },
  { id: 'E018', category: 'edge', input: { year: 1945, month: 8,  day: 15, hour: 12, minute: 0,  gender: '여', calendar: 'solar' } },
  { id: 'E019', category: 'edge', input: { year: 2020, month: 2,  day: 29, hour: 20, minute: 0,  gender: '남', calendar: 'solar' } },
  { id: 'E020', category: 'edge', input: { year: 1955, month: 1,  day: 5,  hour: 1,  minute: 30, gender: '여', calendar: 'solar' } },
];
